# Generated by Django 5.2.8 on 2025-11-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название Бренда')),
                ('type_car', models.CharField(choices=[('Седан', 'Седан'), ('Грузовой', 'Грузовой'), ('Спортивный', 'Спортивный'), ('Внедорожники', 'Внедорожники')], default=None, max_length=15, verbose_name='Тип машины')),
            ],
            options={
                'verbose_name': 'Бранд',
                'verbose_name_plural': 'Бранды',
            },
        ),
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Модель')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='product.brandcar', verbose_name='Бранл')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модель',
            },
        ),
    ]
